# Generated by Django 3.2.2 on 2021-05-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction_app', '0006_commission_item_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBiddings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estimated_price', models.IntegerField()),
                ('old_bid', models.IntegerField()),
                ('current_bid', models.IntegerField()),
                ('bidding_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction_app.item')),
            ],
        ),
    ]
