# Generated by Django 3.2.2 on 2021-05-24 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction_app', '0007_storebiddings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreBiddings',
            new_name='StoreBidding',
        ),
    ]
