# Generated by Django 3.2.2 on 2021-05-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0008_rename_storebiddings_storebidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebidding',
            name='estimated_price',
        ),
    ]
