# Generated by Django 3.2.2 on 2021-05-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0011_jointaccountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='New Item', max_length=255),
        ),
    ]
