# Generated by Django 3.2.2 on 2021-05-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0013_auto_20210531_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
