# Generated by Django 3.2.2 on 2021-05-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0014_rename_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(auto_now=True),
        ),
    ]
